### ISSUE TITLE
部分代码是多余的

### ISSUE THREAD

**Issue by dellyoung** [ConardLi/ConardLi.github.io#7]
读了下发现部分代码是多余的：

经过isObject后，显然(Number String Boolean Symbol Undefined Null)这些类型都是不会往下走的而是直接返回的

但是发现cloneOtherType还是有对（Number String Boolean Symbol ）的处理，我认为后面应该是没有必要再处理的

**Comment by lianlilin** [comment]
> 读了下发现部分代码是多余的：
> 
> 经过isObject后，显然(Number String Boolean Symbol Undefined Null)这些类型都是不会往下走的而是直接返回的
> 
> 但是发现cloneOtherType还是有对（Number String Boolean Symbol ）的处理，我认为后面应该是没有必要再处理的

是为了处理类似于这种情况吧？
`
let a = new Boolean();
console.log(Object.prototype.toString.call(a)); // [object Boolean]
`

**Comment by dellyoung** [comment]
> > 读了下发现部分代码是多余的：
> > 经过isObject后，显然(Number String Boolean Symbol Undefined Null)这些类型都是不会往下走的而是直接返回的
> > 但是发现cloneOtherType还是有对（Number String Boolean Symbol ）的处理，我认为后面应该是没有必要再处理的
> 
> 是为了处理类似于这种情况吧？
> `let a = new Boolean();`
> `console.log(Object.prototype.toString.call(a)); // [object Boolean]`

有道理，不过我又发现没有对属性名为Symbol类型进行处理。处理这个需要用getOwnPropertySymbols这个方法
